---
ID: "f4bd8e16-8685-4bf1-b17e-1f24c121dc3b"
Parent: "977eda35-7dc5-4e34-817d-3817cbdc6dc0"
Template: "977eda35-7dc5-4e34-817d-3817cbdc6dc0"
Path: /sitecore/templates/Project/Sitecore/Tenant/__Standard Values
DB: master
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20190408T214104Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\Admin
