---
ID: "9ece1b9b-68dd-4a92-884f-410d28023838"
Parent: "e3dced0f-c342-42fc-bd37-2ad2924728d4"
Template: "fb3e3034-33f8-4ce8-be98-dd05010f4c22"
Path: /sitecore/content/Sitecore/Styleguide/Presentation/Rendering Variants/RichText/Default
DB: master
SharedFields:
- ID: "f6d8a61c-2f84-4401-bd24-52d2068172bc"
  Hint: __Originator
  Value: "{8F3094F8-34E0-4B48-913C-0DE361D3FBD9}"
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20190408T214405Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\Admin
