---
ID: "cfd4f9ef-af6d-47b2-8d1d-88c1aa4f09ad"
Parent: "bda146e9-1cd3-4955-a2da-6676f677562f"
Template: "bda146e9-1cd3-4955-a2da-6676f677562f"
Path: /sitecore/templates/Project/Sitecore/Fruit/__Standard Values
DB: master
SharedFields:
- ID: "f1a1fe9e-a60c-4ddb-a3a0-bb5b29fe732e"
  Hint: __Renderings
  Type: layout
  Value: |
    <r xmlns:xsd="http://www.w3.org/2001/XMLSchema">
      <d
        id="{FE5D7FDF-89C0-4D99-9AA3-B5FBD009C9F3}"
        l="{BCFC7537-EFF4-434C-96F5-BF4F55FD175B}" />
      <d
        id="{0B4A31C9-712D-4578-A396-2DDC0F34B63A}"
        l="{72C595AD-68BB-44BC-B5CD-2A857039515F}" />
      <d
        id="{73966209-F1B6-43CA-853A-F1DB1C9A654B}"
        l="{A57C19C2-8EE3-4DEC-AA39-0B8D522D59EB}">
        <r
          id="{86F838F5-7E87-45BB-876F-C021324AC8B0}"
          par="TitleField=Title&amp;BodyField=Benefit"
          uid="{F713F93A-D077-4F3E-818D-2689A138A840}" />
      </d>
    </r>
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20180312T143031Z
