---
ID: "b6541eac-2797-4c2a-9d4a-f5ca330659f7"
Parent: "ff9b09f0-453d-47da-a7b9-0274c8d35de9"
Template: "fb3e3034-33f8-4ce8-be98-dd05010f4c22"
Path: /sitecore/content/Sitecore/Styleguide/Presentation/Rendering Variants/Aggregated Facet Filter/Default
DB: master
SharedFields:
- ID: "e1d5adba-8348-4127-9bb6-455936653839"
  Hint: CssClass
  Value: horizontal
- ID: "f6d8a61c-2f84-4401-bd24-52d2068172bc"
  Hint: __Originator
  Value: "{D7A9339F-0B5E-43FC-918F-8E2527255354}"
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20190919T114252Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\Admin
