---
ID: "148f427e-75fd-4822-a302-9ff0837673ca"
Parent: "bb53eae2-ae73-42d2-a642-80cea1ed41ef"
Template: "e24de305-c60f-47d1-97c0-de121d6831d0"
Path: /sitecore/content/Sitecore/Styleguide/Presentation/Cache Settings/Component Cache Settings
DB: master
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20200225T102036Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\Admin
