---
ID: "25b8bea5-9c9e-40f9-a7e1-6b1edfd70ae5"
Parent: "b291f15d-674f-4036-9b6a-976deaab587d"
Template: "e269fbb5-3750-427a-9149-7aa950b49301"
Path: /sitecore/templates/Foundation/Shared Content/Shared Datasources/Shared Datasource Configuration/Datasource configuration
DB: master
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20160504T141921Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\admin
