---
ID: "072f238f-aca5-46c3-b5ec-79fe22113893"
Parent: "a3271e0e-3a17-45b4-9ab0-3dd3a50d5a66"
Template: "25d85d7b-44ca-4fe6-a1cc-feccffaca95c"
Path: /sitecore/content/Sitecore/Styleguide/Home/Components/Security
DB: master
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "077d984e-2053-4761-8d2f-4c3ab3b8833f"
      Hint: Title
      Value: Security
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20190509T123526Z
    - ID: "4e0720e9-9d50-4ddc-87cf-ecd65e8e94c8"
      Hint: NavigationTitle
      Value: Security
