---
ID: "bb53eae2-ae73-42d2-a642-80cea1ed41ef"
Parent: "a61471c1-1bd0-4bca-861a-3b4ce168755b"
Template: "26fce9bf-0256-458d-8281-a713a5bf5520"
Path: /sitecore/content/Sitecore/Styleguide/Presentation/Cache Settings
DB: master
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20190408T214323Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\Admin
